Day 14 Jun, Youngsang
weitzman-musa/30DayMapChallenge pull request #49
Opened 2024-11-10 04:46 UTC by yjmark

## Checklist

- [ x ] You have included a thumbnail image
- [ x ] You have created a new Markdown file to describe your map
- [ x ] You have put _at least_ your name and the map day in the pull request

2024-11-11 13:51 UTC, mjumbewu requested changes
Just a few small changes requested below.

2024-11-11 13:51 UTC, mjumbewu commented on _maps_2024/10-youngsang-jun.md
> +![Screenshot of interactive map](assets/thumbnails/10-youngsang-jun.jpg)
It looks like you're missing the year from this URL here. Same change for your other images.

```suggestion
![Screenshot of interactive map](assets/thumbnails/2024/10-youngsang-jun.jpg)
```

2024-11-11 13:51 UTC, mjumbewu commented on _maps_2024/14-youngsang-jun.md
> +![Screenshot of interactive map](assets/thumbnails/14-youngsang-jun.jpg)
```suggestion
![Screenshot of interactive map](assets/thumbnails/2024/14-youngsang-jun.jpg)
```

2024-11-11 13:51 UTC, mjumbewu commented on _maps_2024/16-youngsang-jun.md
> +![Screenshot of interactive map](assets/thumbnails/16-youngsang-jun.jpg)
```suggestion
![Screenshot of interactive map](assets/thumbnails/2024/16-youngsang-jun.jpg)
```

2024-11-11 15:33 UTC, mjumbewu approved these changes
Looks good to me!

2024-11-11 15:33 UTC, merged

2024-11-12 21:31 UTC, bairunnn commented
great work, Jun!